AppBundle\Entity\Album:
    type: entity
    repositoryClass: "AppBundle\\Repository\\AlbumRepository"
    id:
        id:
            type: integer
            generator:
                strategy: AUTO

    fields:
        name:
            type: string
            length: 120

    oneToMany:
        medias:
          targetEntity: "AppBundle\\Entity\\Media"
          mappedBy: album