AppBundle\Entity\Media:
    type: entity
    inheritanceType: SINGLE_TABLE
    discriminatorColumn:
        name: discr
        type: string
    discriminatorMap:
        picture: Picture
        video: Video
    id:
        id:
            type: integer
            generator:
                strategy: AUTO

    fields:
        description:
            type: text
            nullable: true
        updatedAt:
            type: datetime

    embedded:
        file:
          class: "Vich\\UploaderBundle\\Entity\\File"

    manyToOne:
        album:
          targetEntity: "AppBundle\\Entity\\Media"
          inversedBy: medias
          joinColumn:
            name: album_id
            referencedColumnName: id
