AppBundle\Entity\Tag:
    type: entity
    id:
        id:
            type: integer
            generator:
                strategy: AUTO

    fields:
        label:
            type: string
            length: 120