AppBundle\Entity\Album:
    constraints:
        - Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity:
            fields: [name]
            message: 'Un album de ce nom existe déjà'
    properties:
        name:
            - NotBlank: ~