AppBundle\Entity\Tag:
    constraints:
        - Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity:
            fields: [label]
            message: 'Un tag de ce nom existe déjà'
    properties:
        label:
            - NotBlank: ~